auth_plugin /mosquitto/go-auth.so
auth_opt_backends http
auth_opt_http_host mqtt-auth
auth_opt_http_port 9090
auth_opt_http_getuser_uri /auth
auth_opt_http_aclcheck_uri /acl
auth_opt_http_response_mode status
