#!/usr/bin/env node
/**
 * Single source of truth for the ClankerIdentity ABI.
 *
 * Reads the compiled Foundry artifact and (re)writes the hand-consumed ABI
 * copies used by the TS/JS packages, so they can never drift from the deployed
 * contract:
 *   - identity-service/src/abi/clanker-identity.ts   (full ABI, `as const`)
 *   - clanker-cli/lib/clanker-identity-abi.mjs        (full ABI, plain ESM)
 *
 * Usage:
 *   node scripts/gen-abi.mjs           # regenerate the ABI files
 *   node scripts/gen-abi.mjs --check   # fail (exit 1) if committed files are stale
 *
 * Run this after any change to chain/src/ClankerIdentity.sol.
 */
import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const CHAIN_DIR = join(ROOT, "chain");
const ARTIFACT = join(CHAIN_DIR, "out", "ClankerIdentity.sol", "ClankerIdentity.json");

const TS_OUT = join(ROOT, "identity-service", "src", "abi", "clanker-identity.ts");
const MJS_OUT = join(ROOT, "clanker-cli", "lib", "clanker-identity-abi.mjs");
const NODE_CLIENT_TS_OUT = join(
  ROOT,
  "identity-node-client",
  "src",
  "abi",
  "clanker-identity.ts",
);

const check = process.argv.includes("--check");

function forgeOnPath() {
  try {
    execFileSync("bash", ["-lc", "command -v forge >/dev/null"], { stdio: "ignore" });
    return true;
  } catch {
    return false;
  }
}

function ensureArtifact() {
  if (existsSync(ARTIFACT)) return true;
  if (!forgeOnPath()) {
    console.warn(
      `[gen-abi] forge not on PATH and no artifact at ${ARTIFACT}; skipping.`,
    );
    return false;
  }
  console.log("[gen-abi] artifact missing — running `forge build`...");
  execFileSync("forge", ["build"], { cwd: CHAIN_DIR, stdio: "inherit" });
  return existsSync(ARTIFACT);
}

function loadAbi() {
  const artifact = JSON.parse(readFileSync(ARTIFACT, "utf8"));
  if (!Array.isArray(artifact.abi)) {
    throw new Error(`No .abi array in ${ARTIFACT}`);
  }
  return artifact.abi;
}

const HEADER = [
  "// AUTO-GENERATED by scripts/gen-abi.mjs from the Foundry artifact.",
  "// Do NOT edit by hand. Run `node scripts/gen-abi.mjs` after changing",
  "// chain/src/ClankerIdentity.sol, then commit the regenerated file.",
].join("\n");

function renderTs(abi) {
  return `${HEADER}\nexport const clankerIdentityAbi = ${JSON.stringify(abi, null, 2)} as const;\n`;
}

function renderMjs(abi) {
  return `${HEADER}\nexport const clankerIdentityAbi = ${JSON.stringify(abi, null, 2)};\n`;
}

function main() {
  if (!ensureArtifact()) {
    // Nothing we can do without an artifact; treat as non-fatal skip.
    process.exit(0);
  }
  const abi = loadAbi();
  const targets = [
    { path: TS_OUT, content: renderTs(abi), label: "identity-service ABI (.ts)" },
    { path: MJS_OUT, content: renderMjs(abi), label: "clanker-cli ABI (.mjs)" },
    {
      path: NODE_CLIENT_TS_OUT,
      content: renderTs(abi),
      label: "identity-node-client ABI (.ts)",
    },
  ];

  if (check) {
    const stale = [];
    for (const t of targets) {
      const current = existsSync(t.path) ? readFileSync(t.path, "utf8") : "";
      if (current !== t.content) stale.push(t);
    }
    if (stale.length > 0) {
      console.error(
        "[gen-abi] ABI files are stale (out of sync with the contract):",
      );
      for (const t of stale) console.error(`  - ${t.path}`);
      console.error("Run `node scripts/gen-abi.mjs` and commit the result.");
      process.exit(1);
    }
    console.log("[gen-abi] ABI files are up to date.");
    return;
  }

  for (const t of targets) {
    writeFileSync(t.path, t.content);
    console.log(`[gen-abi] wrote ${t.label} -> ${t.path}`);
  }
}

main();
